name: Template tests

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: https://gitea.com/actions/checkout@v4

      - name: Run template tests
        run: bash tests/run_test.sh
